DELETE FROM "OMS_ZF"."DEVICE";
DROP TABLE "OMS_ZF"."DEVICE";

DELETE FROM "OMS_ZF"."DEVICE_SCADA_INFO_TYPE";
DROP TABLE "OMS_ZF"."DEVICE_SCADA_INFO_TYPE";

DELETE FROM "OMS_ZF"."DEVICE_SCADA_INFO_RULE";
DROP TABLE "OMS_ZF"."DEVICE_SCADA_INFO_RULE";

DELETE FROM "OMS_ZF"."DEVICE_SCADA_REGEX";
DROP TABLE "OMS_ZF"."DEVICE_SCADA_REGEX";
